name: searxer
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  html: ^0.13.4+1
  url_launcher: ^5.0.2
  html_unescape: ^1.0.1+2
  autocomplete_textfield: ^1.6.6
  xml: ^3.4.1
  fluttertoast: ^3.1.0
  shared_preferences: ^0.5.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/searx.webp"

flutter:
  uses-material-design: true
  fonts:
  - family: Material Design Icons
    fonts:
    - asset: fonts/materialdesign/materialdesignicons-webfont.ttf
  assets:
  - assets/icons/searx.webp